package com.kodilla.exception.test;

public class ExceptionHandling {

    public static void main(String[] args) {

        SecondChallenge sc = new SecondChallenge();

/*        try {
            sc.probablyIWillThrowException(0.5, 3.4);
        } catch(Exception e) {
            System.out.println("Message of exception: "+e);
        } finally {
            System.out.println("Call finally!");
        }           */
    }

}
